<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="text-uppercase section-heading">Términos y Condiciones</h2>
            </div>
            <p style="text-align: justify;"><span>Este documento constituye un Acuerdo conforme los términos descritos más adelante y describe los términos y condiciones generales (los "Términos y Condiciones Generales") y las políticas de privacidad (las "Políticas de Privacidad") aplicables al acceso y uso de los servicios ofrecidos por Macro Show "Su Casa Musical" dentro del sitio y/u otros dominios (urls) relacionados (en adelante "macroshow.com" o el "sitio"), en donde éstos Términos y Condiciones se encuentren. Cualquier persona que desee acceder, suscribirse o usar el sitio o los Servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales y las Políticas de Privacidad, junto con todas las demás políticas y principios que rigen macroshow.com y que son incorporados al presente sitio directamente o por referencia o que son explicados o detallados en otras secciones del sitio. En consecuencia, todas las visitas, los contratos y transacciones que se realicen en este sitio, así como sus efectos jurídicos, quedarán regidos por estas Políticas y sometidos a la legislación aplicable en la República del Ecuador.</span></p>
            <p style="text-align: justify;"><span>Los Términos y Condiciones y las Políticas de Privacidad contenidos en este instrumento se aplicarán y se entenderán como parte integral de todos los actos y contratos que se ejecuten o celebren mediante los sistemas de oferta y comercialización comprendidos en este sitio, entre los usuarios de macroshow.com (en adelante "MACRO SHOW" o "la Empresa", indistintamente), y por cualquiera de las otras sociedades o empresas que sean filiales o vinculadas a ella, y que hagan uso de este sitio, a las cuales se las denominará en adelante también en forma indistinta como las "Empresas", o bien la "Empresa Oferente", el "Proveedor" o la "Empresa Proveedora", según convenga al sentido del texto.</span></p>
            <p style="text-align: justify;"><span>En caso que las Empresas hubieran fijado sus propios Términos y Condiciones y sus Políticas de Privacidad para los actos y contratos que realicen en este sitio, ellas aparecerán en esta página señalada con un link o indicada como parte de la promoción de sus ofertas y promociones y prevalecerán sobre éstas. CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES Y LAS POLÍTICAS DE PRIVACIDAD, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS. LA ACEPTACIÓN DE ESTOS TÉRMINOS Y CONDICIONES GENERALES Y LAS POLÍTICAS DE PRIVACIDAD CONSTITUYE UN ACUERDO ENTE MACRO SHOW Y EL USUARIO. El usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad de MACRO SHOW así como en los demás documentos incorporados a los mismos por referencia, previo a su registro como usuario de macroshow.com, a la adquisición de productos o entrega de cualquier dato con cualquier fin.</span></p>
            <p style="text-align: justify;"><span>Si el usuario hiciera uso del sitio de MACRO SHOW, ello implicará la aceptación plena de las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de MACRO SHOW. Por dicha utilización del sitio o sus servicios, el usuario se obligará a cumplir expresamente con las mismas, no pudiendo alegar el desconocimiento de tales Términos y Condiciones Generales y de la Política de Privacidad.</span></p>
            <p><strong><span>1. CAPACIDAD LEGAL</span></strong></p>
            <p style="text-align: justify;"><span>Los servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad y los menores de edad. Los actos que éstos realicen en este sitio serán responsabilidad de sus padres, tutores, encargados o curadores, y por tanto se considerarán realizados por éstos en ejercicio de la representación legal con la que cuentan. Quien registre un usuario como empresa, deberá tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.</span></p>
            <p><strong><span>2. REGISTRO Y USO DEL SITIO</span></strong></p>
            <p style="text-align: justify;"><span>Es obligatorio completar el formulario de registro en todos sus campos con datos válidos para convertirse en usuario autorizado de macroshow.com (el "Miembro" MACRO SHOW o el "Usuario"), acceder a las promociones, y para la adquisición de productos y/o servicios ofrecidos en este sitio. El futuro miembro MACRO SHOW deberá completar el formulario de registro con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. MACRO SHOW podrá utilizar diversos medios para identificar a sus miembros, pero MACRO SHOW NO se responsabiliza por la certeza de los Datos Personales provistos por sus usuarios. Los usuarios garantizan y responden, en cualquier caso, de la exactitud, veracidad, vigencia y autenticidad de los Datos Personales ingresados. Cada miembro sólo podrá ser titular de 1 (una) cuenta MACRO SHOW, no pudiendo acceder a más de 1 (una) cuenta MACRO SHOW con distintas direcciones de correo electrónico o falsificando, modificando o alterando sus datos personales de cualquier manera posible. Si se verificara o sospechara un uso fraudulento, malintencionado o contrario a estos Términos y Condiciones o contrarios a la buena fe, MACRO SHOW tendrá el derecho inapelable de dar por terminados los créditos, dar de baja las cuentas y hasta iniciar acciones legales contra los infractores.</span></p>
            <p style="text-align: justify;"><span>MACRO SHOW se reserva el derecho de solicitar comprobantes o datos adicionales a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitación, MACRO SHOW podrá dar de baja la compra efectuada, sin que ello genere derecho alguno a resarcimiento, pago o indemnización.</span></p>
            <p style="text-align: justify;"><span>El miembro, una vez registrado, dispondrá de su dirección de correo electrónico y una clave secreta (en adelante la "Clave") que le permitirá el acceso personalizado, confidencial y seguro. En caso de poseer estos datos, el usuario tendrá la posibilidad de cambiar la clave de acceso, para lo cual deberá sujetarse al procedimiento establecido en el sitio respectivo. El usuario se obliga a mantener la confidencialidad de su clave de acceso, asumiendo totalmente la responsabilidad por el mantenimiento de la confidencialidad de su clave secreta registrada en este sitio web, la cual le permite solicitar servicios y obtener información (la "Cuenta"). Dicha clave es de uso personal, y su entrega a terceros no involucra responsabilidad de MACRO SHOW o de las empresas en caso de utilización indebida, negligente o incorrecta.</span></p>
            <p style="text-align: justify;"><span>El usuario será responsable por todas las operaciones efectuadas en y desde su cuenta, pues el acceso a la misma está restringido al ingreso y uso de una clave secreta, de conocimiento exclusivo del usuario. El miembro se compromete a notificar a MACRO SHOW en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su cuenta o clave, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión, préstamo o transferencia de la clave o cuenta bajo ningún título.</span></p>
            <p style="text-align: justify;"><span>MACRO SHOW se reserva el derecho de rechazar cualquier solicitud de registro o de cancelar un registro previamente aceptado, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</span></p>
            <p><strong><span>3. MODIFICACIONES DEL ACUERDO</span></strong></p>
            <p style="text-align: justify;"><span>MACRO SHOW podrá modificar los Términos y Condiciones Generales en cualquier momento, haciendo públicos en el sitio los términos modificados. Todos los términos modificados entrarán en vigor a los 10 (diez) días de su publicación. Dentro de los 5 (cinco) días siguientes a la publicación de las modificaciones introducidas, el usuario deberá comunicar por correo electrónico si no acepta las mismas; en ese caso quedará disuelto el vínculo contractual y será inhabilitado como miembro. Vencido este plazo, se considerará que el usuario acepta los nuevos términos y el contrato continuará vinculando a ambas partes.</span></p>
            <p><strong><span>4. PROCEDIMIENTO PARA HACER USO DE ESTE SITIO DE INTERNET</span></strong></p>
            <p style="text-align: justify;"><span>En los contratos ofrecidos por medio del sitio, la Empresa Oferente informará, de manera inequívoca y fácilmente accesible, los pasos que deberán seguirse para celebrarlos, e informará, cuando corresponda, si el documento electrónico en que se formalice el contrato será archivado y si éste será accesible al miembro. El sólo hecho de seguir los pasos que para tales efectos se indiquen en este sitio para efectuar una compra, equivale a aceptar que efectivamente la Empresa Oferente ha dado cumplimiento a las condiciones contenidas en este apartado. Indicará, además, su dirección de correo postal o electrónico y los medios técnicos a disposición del miembro para identificar y corregir errores en el envío o en sus datos.</span></p>
            <p><strong><span>5. MEDIOS DE PAGO QUE SE PODRÁN UTILIZAR EN EL SITIO</span></strong></p>
            <p style="text-align: justify;"><span>Los productos y servicios ofrecidos en el sitio, salvo que se señale una forma diferente para casos particulares u ofertas de determinados bienes o servicios, sólo pueden ser pagados con los medios que en cada caso específicamente se indiquen. El uso de tarjetas de crédito se sujetará a lo establecido en estos Términos y Condiciones, en relación con su emisor, y a lo pactado en los respectivos Contratos de Apertura y Reglamento de Uso. En caso de contradicción, predominará lo expresado en ese último instrumento. Tratándose de tarjetas bancarias aceptadas en el sitio, los aspectos relativos a éstas, tales como la fecha de emisión, caducidad, cupo, bloqueos, etc., se regirán por el respectivo Contrato de Apertura y Reglamento de Uso, de tal forma que las Empresas no tendrán responsabilidad por cualquiera de los aspectos señalados. El sitio podrá indicar determinadas condiciones de compra según el medio de pago que se utilice por el usuario. MACRO SHOW podrá otorgar descuento en la forma de créditos que los usuarios podrán descontar en su compra. En cada caso MACRO SHOW determinará unilateralmente el monto máximo de créditos que el usuario podrá utilizar en una compra y lo detallará en el sistema, previo a iniciar el proceso de pago. Los créditos utilizados por los usuarios no serán reintegrados en caso de devolución de los productos, por cualquier causa que esto ocurriera.</span></p>
            <p><strong><span>6. FORMACIÓN DEL CONSENTIMIENTO EN LOS CONTRATOS CELEBRADOS A TRAVÉS DE ESTE SITIO</span></strong></p>
            <p style="text-align: justify;"><span>A través del sitio web la empresa realizará ofertas de bienes, que podrán ser aceptadas utilizando los mecanismos que el mismo sitio ofrece para ello. Toda aceptación de oferta quedará sujeta a la condición suspensiva de que MACRO SHOW valide la transacción. En consecuencia, para toda operación que se efectúe en este sitio, la confirmación y/o validación o verificación por parte de MACRO SHOW, será requisito para la formación del consentimiento. Para validar la transacción MACRO SHOW deberá verificar: a) Que valida y acepta el medio de pago ofrecido por el usuario, b) Que los datos registrados por el cliente en el sitio coinciden con los proporcionados al efectuar su aceptación de oferta, c) Que el pago es acreditado por el usuario. Para informar al usuario o consumidor acerca de esta validación, MACRO SHOW deberá enviar una confirmación escrita a la misma dirección electrónica que haya registrado el usuario aceptante de la oferta, o por cualquier medio de comunicación que garantice el debido y oportuno conocimiento del consumidor, o mediante el envío efectivo del producto. El consentimiento se entenderá formado desde el momento en que se envía esta confirmación escrita al usuario y en el lugar en que fue expedida. La oferta efectuada por el usuario es irrevocable salvo en circunstancias excepcionales, tales como que MACRO SHOW cambie sustancialmente la descripción del artículo después de realizada alguna oferta, o que exista un claro error tipográfico.</span></p>
            <p style="text-align: justify;"><strong><span>Aviso Legal:</span></strong>
                <span>&nbsp;La venta y despacho de los productos está condicionada a su disponibilidad y a las existencias de producto. Cuando el producto no se encuentre disponible, MACRO SHOW lo notificará de inmediato al cliente y devolverá el valor total del precio pagado.</span>
            </p>
            <p><strong><span>7. PLAZO DE VALIDEZ DE LA OFERTA Y PRECIO</span></strong></p>
            <p style="text-align: justify;"><span>El plazo de validez de la oferta es aquel que coincide con la fecha de vigencia indicada en la promoción o en virtud del agotamiento de las cantidades de productos disponibles para esa promoción debidamente informados al usuario, o mientras la oferta se mantenga disponible, el menor de éstos plazos. Cuando quiera que en una promoción no se indique una fecha de terminación se entenderá que la actividad se extenderá hasta el agotamiento de los inventarios correspondientes.</span></p>
            <p style="text-align: justify;"><span>Los precios de los productos y servicios disponibles en el sitio, mientras aparezcan en él, solo tendrán vigencia y aplicación en éste y no serán aplicables a otros canales de venta utilizados por las empresas, tales como tiendas físicas, venta telefónica, otros sitios de venta por vía electrónica, catálogos u otros. Los precios de los productos ofrecidos en el sitio están expresados en USD salvo que se manifieste lo contrario. Los precios ofrecidos corresponden exclusivamente al valor del bien ofrecido y no incluyen gastos de transporte, manejo, envío, accesorios que no se describan expresamente ni ningún otro ítem adicional.</span></p>
            <p style="text-align: justify;"><span>Adicionalmente, es posible que cierto número de productos puedan tener un precio incorrecto. De existir un error tipográfico en alguno de los precios de los productos, si el precio correcto del artículo es más alto que el que figura en la página, a nuestra discreción, MACRO SHOW lo contactará antes de que el producto sea enviado, o cancelaremos el pedido y le notificaremos acerca de la cancelación.</span></p>
            <p style="text-align: justify;"><span>MACRO SHOW podrá modificar cualquier información contenida en este sitio, incluyendo las relacionadas con mercaderías, precios, existencias y condiciones, en cualquier momento y sin previo aviso, hasta el momento de recibir una aceptación de compra.</span></p>
            <p><strong><span>8. PROMOCIONES</span></strong></p>
            <p style="text-align: justify;"><span>Las promociones que se ofrezcan en este sitio web no son necesariamente las mismas que ofrezcan otros canales de venta utilizados por MACRO SHOW, tales como tiendas físicas, venta telefónica, catálogos u otros, a menos que se señale expresamente en este sitio o en la publicidad que se realice para cada promoción. Cuando el sitio ofrezca promociones que consistan en la entrega gratuita o rebajada de un producto por la compra de otro, el despacho del bien que se entregue gratuitamente o a precio rebajado, se hará en el mismo lugar en el cual se despacha el producto comprado. La Empresa Oferente somete sus promociones y actividades promocionales al cumplimiento de las normas vigentes y específicamente a las disposiciones legales vigentes.</span></p>
            <p style="text-align: justify;"><span>Además de los términos y condiciones generales establecidos en este documento, cuando Macro Show realice promociones en vallas publicitarias, radio, televisión u otros medios publicitarios, aplican adicionalmente los siguientes Términos y Comisiones específicos:</span></p>
            <ol>
                <li><span>El uso del cupón de descuento es completamente gratuito.</span></li>
                <li><span>Cuando se ofrezcan cupones de descuento, se señalará en la publicidad, el valor del cupón, la suma mínima de compra para poder redimir el bono y las fechas válidas para su redención.</span></li>
                <li><span>El cupón de descuento aplica para compras realizadas exclusivamente en la página macroshow.com</span></li>
                <li><span>Podrá hacer uso del bono de descuento cualquier persona natural mayor de dieciocho (18) años.</span></li>
                <li><span>No es acumulable con otras promociones.</span></li>
                <li><span>El uso del bono solamente podrá ser usado una vez por cada cliente.</span></li>
                <li><span>Al hacer una compra con el cupón se entiende que el consumidor ha aceptado íntegramente los tanto los Términos y Condiciones generales de la página así como estos Términos y Condiciones particulares.</span></li>
            </ol>
            <p><strong><span>9. DESPACHO DE LOS PRODUCTOS</span></strong></p>
            <p style="text-align: justify;"><span>Los productos adquiridos a través del sitio se sujetarán a las condiciones de despacho y entrega elegidas por el usuario y disponibles en el sitio. La información del lugar de envío es de exclusiva responsabilidad del usuario. Los plazos elegidos para el despacho y entrega, se cuentan desde que la Empresa Oferente haya validado la orden de compra y el medio de pago utilizado, y se consideran días hábiles para el cumplimiento de dicho plazo. Los pedidos serán despachados de los depósitos de MACRO SHOW dos (2) días hábiles después de finalizada la venta. MACRO SHOW comunicará por correo electrónico a los usuarios los datos para que pueda realizar el seguimiento del estado del envío por Internet.</span></p>
            <p style="text-align: justify;"><span>Si el usuario se encontrara ausente cuando se le visita para dejar el pedido, el correo dejará un aviso en el que figure la hora de la visita. Pasadas las 48 horas del primer intento, el despachador regresará al domicilio para efectuar la entrega del pedido. En caso que nuevamente no se encuentre al usuario, el envío será reintegrado a MACRO SHOW, debiendo el usuario ponerse en contacto con nuestras oficinas para coordinar una nueva entrega cuyo costo estará a exclusivo cargo del usuario.</span></p>
            <p style="text-align: justify;"><span>Advertencia: Macro Show no puede garantizar el envío a algunas regiones del país de productos considerados sobre-dimensionados o con peso excesivo por las empresas de correo. Cuando esto suceda, nos reservamos el derecho de revocar los pedidos que se encuentren en estas condiciones, caso en el cual la orden será reversada y el valor del precio será reembolsado al cliente en el menor tiempo posible. Las entregas en lugares remotos podrán tomar mas tiempo que el establecido en esta cláusula.</span></p>
            <p><strong><span id="return_policy">10. POLÍTICA DE DEVOLUCIONES</span></strong></p>
            <p style="text-align: justify;">En casos de cambios de producto y/o devoluciones de compras online, debe comunicarse con nosotros a través de los siguientes canales para registrar su requerimiento en nuestro sistema.</p>
            <ul>
                <li><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Teléfono: (03) 2964196</li>
                <li><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Celular: 0988428234</li>
                <li><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>Correo electrónico: <span><a href="mailto:macroshow1979@hotmail.com">macroshow1979@hotmail.com</a></span></li>
            </ul>
            <p style="text-align: justify;">La persona encargada le indicará el procedimiento que debe seguir para realizar la operación solicitada. La devolución del dinero por nuestros productos se realizará solo para los siguientes casos:</p>
            <ul>
                <li><strong>Mercadería Cambiada:</strong> Le llegó un artículo que no tiene las mismas características al registrado en la orden. Tiene máximo 7 días hábiles para notificar desde la fecha de emisión de su factura. Caso contrario no aplica reembolso.</li>
                <li><strong>Mercadería Incompleta:</strong> Cuando el producto no ha llegado con las piezas completas o no llega la orden completa, tiene máximo 7 días hábiles para notificar desde la fecha de emisión de su factura. Caso contrario no aplica reembolso.</li>
                <li><strong>Mercadería no funciona:</strong> Revisar políticas de garantía.</li>
                <li><strong>Mercadería no llegó:</strong> Si en 15 días laborales desde la emisión de su factura no llega la orden, Ud. puede solicitar el reembolso de su dinero.</li>
            </ul>
            <p style="text-align: justify;">Aceptamos sus devoluciones siempre que se encuentren en buen estado, sin uso, con todos sus accesorios, caja original y manuales completos. En el caso de que un artículo sea devuelto en una condición inapropiada, tendríamos que enviárselo de vuelta.</p>
            <p style="text-align: justify;">Nuestro asesor encargado le solicitará los datos de su cuenta y coordinará con Ud. el retiro de la mercadería.</p>
            <p style="text-align: justify;">Retiraremos la mercadería donde Ud. nos indique o también puede entregarla en la Av. Daniel Leon Borja y Juan de Lavalle.</p>
            <p style="text-align: justify;">Envíenos un correo electrónico indicando la cédula, ciudad, día y hora en que se ha dejado el paquete que retornará y el número de guía asociada, para poder efectuar un eficaz seguimiento.</p>
            <p style="text-align: justify;">Los gastos de envío incurridos en las devoluciones y cambios serán cubiertos por Macro Show cuando se entregue en la dirección mencionada.</p>
            <p style="text-align: justify;">El valor del reembolso se verá reflejado en su cuenta bancaria en un lapso de 3 a 5 días hábiles desde el momento en que recibimos la devolución de la mercadería.</p>
            <p><strong><span>11. RESPONSABILIDAD DE MACRO SHOW</span></strong></p>
            <p style="text-align: justify;"><span>MACRO SHOW hará lo posible dentro de sus capacidades para que la transmisión del sitio sea ininterrumpida y libre de errores. Sin embargo, dada la naturaleza de la Internet, dichas condiciones no pueden ser garantizadas. En el mismo sentido, el acceso del usuario a la cuenta puede ser ocasionalmente restringido o suspendido con el objeto de efectuar reparaciones, mantenimiento o introducir nuevos Servicios. MACRO SHOW no será responsable por pérdidas (i) que no hayan sido causadas por el incumplimiento de sus obligaciones; (ii) lucro cesante o pérdidas de oportunidades comerciales; (iii) cualquier daño indirecto.</span></p>
            <p><strong><span>12. TÉRMINOS DE LEY</span></strong></p>
            <p style="text-align: justify;"><span>Este acuerdo será gobernado e interpretado de acuerdo con las leyes de Ecuador, sin dar efecto a cualquier principio de conflictos de ley. Si alguna disposición de estos Términos y Condiciones es declarada ilegal, o presenta un vacío, o por cualquier razón resulta inaplicable, la misma deberá ser interpretada dentro del marco del mismo y en cualquier caso no afectará la validez y la aplicabilidad de las provisiones restantes.</span></p>
            <p><strong><span>13. NOTIFICACIONES</span></strong></p>
            <p style="text-align: justify;"><span>Cualquier comentario, inquietud o reclamación respecto de los anteriores Términos y Condiciones, la Política de Privacidad, o la ejecución de cualquiera de éstos, deberá ser notificada por escrito a MACRO SHOW a la siguiente dirección: Av. Daniel Leon Borja y Juan de Lavalle Piso 2.</span></p>
        </div>
    </div>
</section>